# These are supported funding model platforms

github: [pytonik, emmamartins] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: pytonik # Replace with a single Patreon username
open_collective: pytonik # Replace with a single Open Collective username
ko_fi: pytonik # Replace with a single Ko-fi username
tidelift: pytonik # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: pytonik # Replace with a single Liberapay username
issuehunt: emmamartins # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
